[package]
name = "palindromo"
version = "0.1.0"
authors = ["AlexisBalderas27 <65316567+AlexisBalderas27@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
